import { LoginForm, type LoginFormValues } from "@/components/LoginForm";
import { getErrorNotification } from "@/utils/getters";
import { Container, Flex, Grid, Paper, Text } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { type GetStaticProps, type NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [isLoading, setIsLoading] = useState(false);
  const router = useRouter();
  useEffect(() => {
    const hasSessionEnded = localStorage.getItem("session-ended");
    if (hasSessionEnded) {
      notifications.show({
        message: "Sesi anda telah habis",
        color: "red",
      });
      localStorage.removeItem("session-ended");
    }
  }, []);
  const onSubmit = async (values: LoginFormValues) => {
    try {
      setIsLoading(true);
      const res = await signIn("credentials", {
        email: values.email,
        password: values.password,
        redirect: false,
      });

      if (res?.error) throw new Error(res?.error);

      if (res?.ok === true) {
        await router.push("/cms");
      }
    } catch (err) {
      getErrorNotification(err);
    } finally {
      setIsLoading(false);
    }
  };
  return (
    <>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        mx={"auto"}
        style={{
          maxWidth: "20rem",
        }}
        mt={"10rem"}
      >
        <Flex direction={"column"}>
          <Paper
            style={{
              flexBasis: "100%",
              height: "100%",
              flexGrow: 0,
              flexShrink: 1,
            }}
          >
            <Grid justify="center">
              <Grid.Col span={12}>
                <Grid justify="center">{/* IMAGE */}</Grid>

                <Text mt={"lg"} fw={"bold"} ta={"center"}>
                  My T3 App
                </Text>

                <Text ta={"center"}>Made by Vultra Digital Asia</Text>
                <LoginForm isLoading={isLoading} onSubmit={onSubmit} />
              </Grid.Col>
            </Grid>
          </Paper>
        </Flex>
      </Container>
    </>
  );
};

export const getStaticProps: GetStaticProps = () => {
  return {
    notFound: false,
    props: {},
  };
};

export default Home;
